name: Deploy to Koyeb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install cURL
      run: sudo apt-get install -y curl

    - name: Deploy to Koyeb
      env:
        KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
      run: |
        curl -X POST "https://app.koyeb.com/v1/apps/e0ac1dda-1e0f-4e11-94a7-df1563c38a95/deployments" \
        -H "Authorization: Bearer $KOYEB_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{}'
