name: Cron Job

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정 update 실행
    - cron: "0 0 1 * *" # 매월 1일 자정 all 실행
  workflow_dispatch:

jobs:
  trigger-scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: PLAYWRIGHT_BROWSERS_PATH=./node_modules/.cache/ms-playwright npx playwright install

      - name: Run daily scraping
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        env:
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
        run: |
          NODE_PATH=./node_modules node server/server.js --task=update

      - name: Run monthly event scraping
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 1 * *'
        env:
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
        run: |
          NODE_PATH=./node_modules node server/server.js --task=all

      - name: Run manually triggered scraping
        if: github.event_name == 'workflow_dispatch'
        env:
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
        run: |
          NODE_PATH=./node_modules node server/server.js --task=all