name: Cron Job

on:
  schedule:
    - cron: '0 22 30 * *'   # 매일 자정 /update 호출
    - cron: '0 0 1 * *'    # 매월 1일 자정 /all 호출

jobs:
  trigger-scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: cd server && npx playwright install

      - name: Send daily update request
        if: github.event.schedule == '0 0 * * *'
        run: curl -X POST https://cvsnew-sloth-hub.koyeb.app/update

      - name: Send monthly event scraping request
        if: github.event.schedule == '0 0 1 * *'
        run: curl -X POST https://cvsnew-sloth-hub.koyeb.app/all
