name: Cron Job

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정 /update 호출
    - cron: "0 0 1 * *" # 매월 1일 자정 /all 호출

jobs:
  trigger-scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Install Playwright Browsers
        run: |
          cd server
          PLAYWRIGHT_BROWSERS_PATH=./node_modules/.cache/ms-playwright npx playwright install

      - name: Debug Playwright Installation
        run: |
          cd server
          ls -la ./node_modules/.cache/ms-playwright

      - name: Run daily scraping
        if: github.event.schedule == '0 0 * * *'
        run: |
          cd server
          node server.js --task=update

      - name: Run monthly event scraping
        if: github.event.schedule == '0 0 1 * *'
        run: |
          cd server
          node server.js --task=all
